import makeWASocket,{DisconnectReason,useMultiFileAuthState} from '@whiskeysockets/baileys';
import qrcode from 'qrcode-terminal';
import pino from 'pino';
import { promises as fs } from 'node:fs';
import { env } from '../env.js';
const logger=pino({level:'info'});const API=env.APP_URL.replace(/\/$/,'');const sessions='./data/wa-auth';
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{...options,headers:{'content-type':'application/json',...(options.headers??{})}});const text=await r.text();let body:any;try{body=JSON.parse(text)}catch{body={error:text}};if(!r.ok)throw new Error(body.error??`HTTP_${r.status}`);return body}
async function run(){await fs.mkdir(sessions,{recursive:true});const {state,saveCreds}=await useMultiFileAuthState(sessions);const sock=makeWASocket({auth:state,logger});sock.ev.on('creds.update',saveCreds);sock.ev.on('connection.update',({connection,lastDisconnect,qr})=>{if(qr){console.log('Scan QR:');qrcode.generate(qr,{small:true})}if(connection==='open')logger.info('WhatsApp bot connected');if(connection==='close'){const code=(lastDisconnect?.error as any)?.output?.statusCode;if(code!==DisconnectReason.loggedOut)setTimeout(run,5000)}});sock.ev.on('messages.upsert',async({messages})=>{const m=messages[0];if(!m?.message||m.key.fromMe)return;const jid=m.key.remoteJid!;const text=(m.message.conversation??m.message.extendedTextMessage?.text??'').trim();if(!text)return;const [cmd,...args]=text.split(/\s+/);try{if(cmd.toLowerCase()==='ping')return void await sock.sendMessage(jid,{text:'Payment-Get online ✅'});if(cmd.toLowerCase()==='help'||cmd.toLowerCase()==='menu')return void await sock.sendMessage(jid,{text:'Payment-Get\n\nPerintah:\nregister nama|username|gmail|hp|password\nlogin username/gmail|password\nsaldo TOKEN\ntransaksi TOKEN PAYMENT_ID\n\nGunakan hanya untuk akun Anda sendiri.'});if(cmd.toLowerCase()==='register'){const [name,username,email,phone,password]=args.join(' ').split('|').map(x=>x?.trim());if(!name||!username||!email||!phone||!password)throw new Error('FORMAT: register nama|username|gmail|hp|password');await api('/auth/register',{method:'POST',body:JSON.stringify({name,username,email,phone,password})});return void await sock.sendMessage(jid,{text:'Registrasi berhasil. Login dengan username/Gmail + password.'})}if(cmd.toLowerCase()==='login'){const [login,password]=args.join(' ').split('|').map(x=>x?.trim());if(!login||!password)throw new Error('FORMAT: login username/gmail|password');const r=await api('/auth/login',{method:'POST',body:JSON.stringify({login,password})});return void await sock.sendMessage(jid,{text:`Login berhasil. Token Anda:\n${r.token}\nSimpan dengan aman.`})}if(cmd.toLowerCase()==='saldo'){const token=args[0];if(!token)throw new Error('FORMAT: saldo TOKEN');const r=await api('/api/v1/balance',{headers:{authorization:`Bearer ${token}`}});return void await sock.sendMessage(jid,{text:`Saldo: Rp ${Number(r.balance).toLocaleString('id-ID')}`})}if(cmd.toLowerCase()==='transaksi'){const token=args[0],paymentId=args[1];if(!token||!paymentId)throw new Error('FORMAT: transaksi TOKEN PAYMENT_ID');const r=await api(`/api/v1/payments/${encodeURIComponent(paymentId)}`,{headers:{authorization:`Bearer ${token}`}});return void await sock.sendMessage(jid,{text:`${r.paymentId}\nStatus: ${r.status}\nNominal: Rp ${Number(r.amount).toLocaleString('id-ID')}\nBayar: Rp ${Number(r.payableAmount).toLocaleString('id-ID')}`})}return void await sock.sendMessage(jid,{text:'Perintah tidak dikenal. Ketik menu.'})}catch(e:any){await sock.sendMessage(jid,{text:`Gagal: ${e.message}`})}})}
run().catch(e=>logger.error(e));
